import type { Metadata } from "next";
import "../globals.css";
import Header from "./_components/header";
import Footer from "./_components/footer";
import { auth } from "@/lib/auth";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section className="flex flex-col min-h-svh">
      <Header />
      <main className="flex-grow py-4">
        {children}
      </main>
      <Footer />
    </section>
  );
}
